baseURL = "www.agileplus.co"
languageCode = "cn-zh"
title = "敏捷家AgilePlus"
themesDir = "./themes"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.svg"
    alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
    meta_description = "敏捷家是一群信仰敏捷的人“居住”的地方。AgilePlus顾名思义就是敏捷+。如下： 敏捷+开发 敏捷+产品 敏捷+运维（devops） 敏捷+hr 敏捷+硬件 敏捷+营销 敏捷+教育 敏捷+家庭 。"
    meta_og_title = "敏捷家AgilePlus"
    meta_og_type = "website"
    meta_og_url = "www.agileplus.co"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "敏捷家是一群信仰敏捷的人“居住”的地方。AgilePlus顾名思义就是敏捷+。如下： 敏捷+开发 敏捷+产品 敏捷+运维（devops） 敏捷+hr 敏捷+硬件 敏捷+营销 敏捷+教育 敏捷+家庭 "
    meta_twitter_card = "Bob Jiang"
    meta_twitter_site = "@bobjiang123"
    meta_twitter_creator = "@bobjiang123"

[menu]
  # Main Menu

  [[menu.main]]
      name = "团队"
      url = "/team/"
      weight = 1

  # Footer Menu

  [[menu.footer]]
    name = "联系"
    url = "/contact/"
      weight = 2
